#!/bin/sh

yarn build && yalc publish

cd ../doable
yalc add due-date
rm -rf node_modules
rm -rf .blitz
git clean -fd
git checkout -f
blitz prisma migrate reset --force
yarn install --frozen-lockfile # --verbose

cd ../abledev-due-date-job-request
